import { Eye, EyeOff, LoaderCircle, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { ApiError } from '../services/apiClient';
import { loginAccount, registerAccount, resendRegistrationOtp, verifyRegistrationOtp } from '../services/authApi';
import AuthToast from './AuthToast';
import EmailVerificationStep from './auth/EmailVerificationStep';
import '../styles/auth-popup.css';

const emptyForm = { name: '', username: '', email: '', password: '', confirmPassword: '' };
const OTP_RESEND_COOLDOWN_SECONDS = 60;
const otpErrorState = (error) => {
  const message = (error?.message || '').toLocaleLowerCase();
  if (message.includes('hết hạn') || message.includes('expired')) return 'expired';
  if (message.includes('đã sử dụng') || message.includes('already been used')) return 'alreadyUsed';
  if (message.includes('quá nhiều') || message.includes('too many')) return 'tooManyAttempts';
  return message.includes('otp') || message.includes('mã') || message.includes('invalid') ? 'invalid' : 'error';
};

export default function AuthModal({ mode, onClose, onSubmit, onGoogle, onAuthenticated, verification = {}, backdropClassName = '' }) {
  const [form, setForm] = useState(emptyForm); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [submitting, setSubmitting] = useState(false); const [showPassword, setShowPassword] = useState(false); const [showConfirmation, setShowConfirmation] = useState(false);
  const [registeredEmail, setRegisteredEmail] = useState(''); const [verificationCode, setVerificationCode] = useState(''); const [verificationState, setVerificationState] = useState('idle'); const [cooldownSeconds, setCooldownSeconds] = useState(0);
  const isSignup = mode === 'signup'; const isVerification = mode === 'verify-email'; const email = registeredEmail || verification.email;
  useEffect(() => { const close = (event) => event.key === 'Escape' && onClose(); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [onClose]);
  useEffect(() => { if (!cooldownSeconds) return undefined; const timer = window.setInterval(() => setCooldownSeconds((seconds) => Math.max(0, seconds - 1)), 1000); return () => window.clearInterval(timer); }, [Boolean(cooldownSeconds)]);
  const update = (event) => { const { name, value } = event.target; setForm((current) => ({ ...current, [name]: value })); setError(''); };
  const submit = async (event) => {
    event.preventDefault();
    if (isSignup && !form.name.trim()) return setError('Please enter your full name.'); if (isSignup && !form.username.trim()) return setError('Please enter a username.'); if (!form.email.trim()) return setError(isSignup ? 'Please enter your email.' : 'Please enter your email or username.'); if (isSignup && !/^\S+@\S+\.\S+$/.test(form.email)) return setError('Please enter a valid email address.'); if (!form.password) return setError('Please enter your password.'); if (isSignup && form.password.length < 8) return setError('Password must be at least 8 characters.'); if (isSignup && form.password !== form.confirmPassword) return setError('Passwords do not match.');
    setSubmitting(true); setError('');
    try { const data = isSignup ? await registerAccount({ fullName: form.name.trim(), username: form.username.trim(), email: form.email.trim(), password: form.password }) : await loginAccount({ usernameOrEmail: form.email.trim(), password: form.password }); if (isSignup) { setRegisteredEmail(form.email.trim()); setVerificationCode(''); setVerificationState('idle'); setCooldownSeconds(0); onSubmit?.(null, 'verify-email'); return; } if (data.token) localStorage.setItem('nutribot-auth-token', data.token); onAuthenticated?.(data, mode); setSuccess('Welcome back.'); window.setTimeout(onClose, 700); }
    catch (requestError) { setError(requestError instanceof ApiError ? requestError.message : requestError.message || 'Something went wrong. Please try again.'); } finally { setSubmitting(false); }
  };
  const verifyOtp = async (otpCode) => { if (!email || otpCode.length !== 6) return; setVerificationState('verifying'); try { const data = await verifyRegistrationOtp({ email, otpCode }); localStorage.setItem('nutribot-auth-token', data.token); setVerificationState('verified'); onAuthenticated?.(data, 'verify-email'); } catch (requestError) { setVerificationState(otpErrorState(requestError)); } };
  const resendOtp = async () => { if (!email || cooldownSeconds) return; setVerificationState('resending'); try { await resendRegistrationOtp(email); setVerificationCode(''); setVerificationState('resendSuccess'); setCooldownSeconds(OTP_RESEND_COOLDOWN_SECONDS); } catch (requestError) { setVerificationState(otpErrorState(requestError)); } };
  const backToSignup = () => { setVerificationCode(''); setVerificationState('idle'); setCooldownSeconds(0); verification.onBack?.(); if (!verification.onBack) onSubmit?.(null, 'signup'); };
  if (isVerification) return <div className={`modal-backdrop auth-backdrop ${backdropClassName}`.trim()} role="dialog" aria-modal="true" aria-labelledby="email-verification-title" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="auth-modal auth-modal--verification"><button className="modal-close" type="button" onClick={onClose} aria-label="Close"><X size={19}/></button><EmailVerificationStep {...verification} email={email} code={verificationCode} onCodeChange={(code) => { setVerificationCode(code); setVerificationState('idle'); }} onVerify={verifyOtp} onResend={resendOtp} onBack={backToSignup} verificationState={verificationState} cooldownSeconds={cooldownSeconds}/></div></div>;
  return <><AuthToast error={error} success={success}/><div className={`modal-backdrop auth-backdrop ${backdropClassName}`.trim()} role="dialog" aria-modal="true" aria-labelledby="auth-title" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><form className="auth-modal" onSubmit={submit}><button className="modal-close" type="button" onClick={onClose} aria-label="Close"><X size={19}/></button><p>Welcome to NutriBot</p><h2 id="auth-title">{isSignup ? 'Make nourishment personal.' : 'Welcome back.'}</h2><span>{isSignup ? 'Create an account to save ideas, videos and recipes.' : 'Sign in to continue your healthy routine.'}</span><button className="google-auth" type="button" onClick={onGoogle}><b className="google-mark">G</b><span>Continue with Google</span></button><div className="auth-divider"><span>or use email</span></div>{isSignup && <label>Full name<input required name="name" value={form.name} onChange={update} placeholder="Your name"/></label>}{isSignup && <label>Username<input required name="username" value={form.username} onChange={update} placeholder="Choose a username"/></label>}<label>{isSignup ? 'Email' : 'Email or username'}<input required name="email" type={isSignup ? 'email' : 'text'} value={form.email} onChange={update} placeholder={isSignup ? 'you@example.com' : 'you@example.com or username'}/></label><label>Password<span className="password-input"><input required name="password" type={showPassword ? 'text' : 'password'} minLength={isSignup ? 8 : 1} value={form.password} onChange={update} placeholder="Your password"/><button type="button" onClick={() => setShowPassword((current) => !current)} aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? <EyeOff size={18}/> : <Eye size={18}/>}</button></span></label>{isSignup && <label>Confirm password<span className="password-input"><input required name="confirmPassword" type={showConfirmation ? 'text' : 'password'} value={form.confirmPassword} onChange={update} placeholder="Repeat your password"/><button type="button" onClick={() => setShowConfirmation((current) => !current)} aria-label={showConfirmation ? 'Hide password confirmation' : 'Show password confirmation'}>{showConfirmation ? <EyeOff size={18}/> : <Eye size={18}/>}</button></span></label>}<button className="auth-submit" type="submit" disabled={submitting || Boolean(success)}>{submitting ? <><LoaderCircle className="register-spinner" size={17}/>Please wait...</> : isSignup ? 'Create account' : 'Log in'}</button><button className="auth-switch" type="button" onClick={() => onSubmit?.(null, isSignup ? 'login' : 'signup')}>{isSignup ? 'Already have an account? Log in' : 'New here? Create an account'}</button></form></div></>;
}
